### ISSUE TITLE
Test results which stored in CSV are not populating in Report portal

### ISSUE THREAD

**Issue by Agurul** [Invictum/serenity-reportportal-integration#89]
I have a test results which stored in csv file. I will not use Assertion in my test file due to huge data records validation.
Report portal is not showing any results for my Passed test case.

Is it possible to avail my csv results file from project directory to report portal ? If so please guide me on this how to publish CSV data on report portal?

**Comment by Agurul** [comment]
Any update on this please

**Comment by Invictum** [comment]
@Agurul 
Integration provides only link between Serenity and Report Portal. And you are looking for some kind of import with custom format.

I'm not sure about CSV files, but Report Portal supports xUnit style report import [link](https://reportportal.io/docs/Log-data-import). But it is better to ask a question in Report Portal github scope [here](https://github.com/reportportal/reportportal).

I'm closing this issue because it is not relevant to integration itself.
